/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */

import Page = require('../../../../../base/Page');
import Response = require('../../../../../http/response');
import Understand = require('../../../Understand');
import { ListEachOptions, ListOptions, PageOptions } from '../../../../../interfaces';

declare function FieldValueList(version: Understand, serviceSid: string, fieldTypeSid: string): FieldValueListInstance

interface FieldValueResource {
  /**
   * The account_sid
   */
  account_sid: string;
  /**
   * The date_created
   */
  date_created: Date;
  /**
   * The date_updated
   */
  date_updated: Date;
  /**
   * The field_type_sid
   */
  field_type_sid: string;
  /**
   * The language
   */
  language: string;
  /**
   * The service_sid
   */
  service_sid: string;
  /**
   * The sid
   */
  sid: string;
  /**
   * The url
   */
  url: string;
  /**
   * The value
   */
  value: string;
}

interface FieldValuePayload extends FieldValueResource, Page.TwilioResponsePayload {
}

interface FieldValueSolution {
  fieldTypeSid: string;
  serviceSid: string;
}

interface FieldValueListEachOptions extends ListEachOptions<FieldValueInstance> {
  /**
   * The language
   */
  language?: string;
}

interface FieldValueListOptions extends ListOptions<FieldValueInstance> {
  /**
   * The language
   */
  language?: string;
}

interface FieldValueListPageOptions extends PageOptions<FieldValuePage> {
  /**
   * The language
   */
  language?: string;
}

interface FieldValueListCreateOptions {
  /**
   * The language
   */
  language: string;
  /**
   * The value
   */
  value: string;
}

interface FieldValueListInstance {
  /**
   * Gets context of a single FieldValue resource
   *
   * @param sid - The sid
   */
  (sid: string): FieldValueContext;
  /**
   * create a FieldValueInstance
   *
   * @param opts - Options for request
   *
   * @returns Promise that resolves to processed FieldValueInstance
   */
  create(opts: FieldValueListCreateOptions): Promise<FieldValueInstance>;
  /**
   * create a FieldValueInstance
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  create(opts: FieldValueListCreateOptions, callback: (error: Error | null, items: FieldValueInstance) => any): void;
  /**
   * Streams FieldValueInstance records from the API.
   *
   * This operation lazily loads records as efficiently as possible until the limit
   * is reached.
   *
   * The results are passed into the callback function, so this operation is memory efficient.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  each(opts?: FieldValueListEachOptions): void;
  /**
   * Streams FieldValueInstance records from the API.
   *
   * This operation lazily loads records as efficiently as possible until the limit
   * is reached.
   *
   * The results are passed into the callback function, so this operation is memory efficient.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  each(callback: (item: FieldValueInstance, done: (err?: Error) => void) => void): any;
  /**
   * Gets context of a single FieldValue resource
   *
   * @param sid - The sid
   */
  get(sid: string): FieldValueContext;
  /**
   * Retrieve a single target page of FieldValueInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param targetUrl - API-generated URL for the requested results page
   */
  getPage(targetUrl: string): Promise<FieldValuePage>;
  /**
   * Retrieve a single target page of FieldValueInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param targetUrl - API-generated URL for the requested results page
   * @param callback - Callback to handle processed record
   */
  getPage(targetUrl: string, callback: (error: Error | null, items: FieldValuePage) => any): void;
  /**
   * Lists FieldValueInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  list(opts?: FieldValueListOptions): Promise<FieldValueInstance[]>;
  /**
   * Lists FieldValueInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  list(opts: FieldValueListOptions, callback: (error: Error | null, items: FieldValueInstance[]) => any): void;
  /**
   * Lists FieldValueInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  list(callback: (error: Error | null, items: FieldValueInstance[]) => any): void;
  /**
   * Retrieve a single page of FieldValueInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  page(opts?: FieldValueListPageOptions): Promise<FieldValuePage>;
  /**
   * Retrieve a single page of FieldValueInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  page(opts: FieldValueListPageOptions, callback: (error: Error | null, items: FieldValuePage) => any): void;
  /**
   * Retrieve a single page of FieldValueInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  page(callback: (error: Error | null, items: FieldValuePage) => any): void;
}

declare class FieldValuePage extends Page<Understand, FieldValuePayload, FieldValueResource, FieldValueInstance> {
  constructor(version: Understand, response: Response<string>, solution: FieldValueSolution);

  /**
   * Build an instance of FieldValueInstance
   *
   * @param payload - Payload response from the API
   */
  getInstance(payload: FieldValuePayload): FieldValueInstance;
}

declare class FieldValueInstance {
  /**
   * @param version - Version of the resource
   * @param payload - The instance payload
   * @param serviceSid - The service_sid
   * @param fieldTypeSid - The field_type_sid
   * @param sid - The sid
   */
  constructor(version: Understand, payload: FieldValuePayload, serviceSid: string, fieldTypeSid: string, sid: string);

  private _proxy: FieldValueContext;
  /**
   * The account_sid
   */
  accountSid: string;
  /**
   * The date_created
   */
  dateCreated: Date;
  /**
   * The date_updated
   */
  dateUpdated: Date;
  /**
   * fetch a FieldValueInstance
   *
   * @returns Promise that resolves to processed FieldValueInstance
   */
  fetch(): Promise<FieldValueInstance>;
  /**
   * fetch a FieldValueInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback: (error: Error | null, items: FieldValueInstance) => any): void;
  /**
   * The field_type_sid
   */
  fieldTypeSid: string;
  /**
   * The language
   */
  language: string;
  /**
   * remove a FieldValueInstance
   *
   * @returns Promise that resolves to processed FieldValueInstance
   */
  remove(): Promise<FieldValueInstance>;
  /**
   * remove a FieldValueInstance
   *
   * @param callback - Callback to handle processed record
   */
  remove(callback: (error: Error | null, items: FieldValueInstance) => any): void;
  /**
   * The service_sid
   */
  serviceSid: string;
  /**
   * The sid
   */
  sid: string;
  /**
   * The url
   */
  url: string;
  /**
   * The value
   */
  value: string;
}

declare class FieldValueContext {
  constructor(version: Understand, serviceSid: string, fieldTypeSid: string, sid: string);

  /**
   * fetch a FieldValueInstance
   *
   * @returns Promise that resolves to processed FieldValueInstance
   */
  fetch(): Promise<FieldValueInstance>;
  /**
   * fetch a FieldValueInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback: (error: Error | null, items: FieldValueInstance) => any): void;
  /**
   * remove a FieldValueInstance
   *
   * @returns Promise that resolves to processed FieldValueInstance
   */
  remove(): Promise<FieldValueInstance>;
  /**
   * remove a FieldValueInstance
   *
   * @param callback - Callback to handle processed record
   */
  remove(callback: (error: Error | null, items: FieldValueInstance) => any): void;
}

export {FieldValueSolution, FieldValueListPageOptions, FieldValuePage, FieldValuePayload, FieldValueInstance, FieldValueContext, FieldValueListEachOptions, FieldValueList, FieldValueResource, FieldValueListCreateOptions, FieldValueListOptions, FieldValueListInstance}
