/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import Version = require('../../base/Version');
import { AuthorizationDocumentList } from './hosted_numbers/authorizationDocument';
import { HostedNumberOrderList } from './hosted_numbers/hostedNumberOrder';


/**
 * Initialize the HostedNumbers version of Preview
 */
declare class HostedNumbers extends Version {
  /**
   * Initialize the HostedNumbers version of Preview
   *
   * @param domain - The twilio domain
   */
  constructor(domain: any);

  readonly authorizationDocuments: AuthorizationDocumentList;
  readonly hostedNumberOrders: HostedNumberOrderList;
}

export = HostedNumbers;
