/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import Version = require('../../base/Version');
import { AvailableAddOnList } from './marketplace/availableAddOn';
import { InstalledAddOnList } from './marketplace/installedAddOn';


/**
 * Initialize the Marketplace version of Preview
 */
declare class Marketplace extends Version {
  /**
   * Initialize the Marketplace version of Preview
   *
   * @param domain - The twilio domain
   */
  constructor(domain: any);

  readonly availableAddOns: AvailableAddOnList;
  readonly installedAddOns: InstalledAddOnList;
}

export = Marketplace;
