/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import Version = require('../../base/Version');
import { ServiceList } from './proxy/service';


/**
 * Initialize the Proxy version of Preview
 */
declare class Proxy extends Version {
  /**
   * Initialize the Proxy version of Preview
   *
   * @param domain - The twilio domain
   */
  constructor(domain: any);

  readonly services: ServiceList;
}

export = Proxy;
