/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import Version = require('../../base/Version');
import { WorkspaceList } from './v1/workspace';


/**
 * Initialize the V1 version of Taskrouter
 */
declare class V1 extends Version {
  /**
   * Initialize the V1 version of Taskrouter
   *
   * @param domain - The twilio domain
   */
  constructor(domain: any);

  readonly workspaces: WorkspaceList;
}

export = V1;
