/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */

import V1 = require('../V1');

declare function CredentialList(version: V1): CredentialListInstance

interface CredentialResource {
}

interface CredentialPayload extends CredentialResource, Page.TwilioResponsePayload {
}

interface CredentialSolution {
}

interface CredentialListInstance {
}

export {CredentialList, CredentialResource, CredentialPayload, CredentialListInstance, CredentialSolution}
