/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */

import Page = require('../../../../../../base/Page');
import Response = require('../../../../../../http/response');
import V2010 = require('../../../../V2010');
import { ListEachOptions, ListOptions, PageOptions } from '../../../../../../interfaces';

declare function IpAccessControlListMappingList(version: V2010, accountSid: string, domainSid: string): IpAccessControlListMappingListInstance

interface IpAccessControlListMappingResource {
  /**
   * The account_sid
   */
  account_sid: string;
  /**
   * The date_created
   */
  date_created: Date;
  /**
   * The date_updated
   */
  date_updated: Date;
  /**
   * The friendly_name
   */
  friendly_name: string;
  /**
   * The sid
   */
  sid: string;
  /**
   * The subresource_uris
   */
  subresource_uris: string;
  /**
   * The uri
   */
  uri: string;
}

interface IpAccessControlListMappingPayload extends IpAccessControlListMappingResource, Page.TwilioResponsePayload {
}

interface IpAccessControlListMappingSolution {
  accountSid: string;
  domainSid: string;
}

interface IpAccessControlListMappingListCreateOptions {
  /**
   * The ip_access_control_list_sid
   */
  ipAccessControlListSid: string;
}

interface IpAccessControlListMappingListEachOptions extends ListEachOptions<IpAccessControlListMappingInstance> {
}

interface IpAccessControlListMappingListOptions extends ListOptions<IpAccessControlListMappingInstance> {
}

interface IpAccessControlListMappingListPageOptions extends PageOptions<IpAccessControlListMappingPage> {
}

interface IpAccessControlListMappingListInstance {
  /**
   * Gets context of a single IpAccessControlListMapping resource
   *
   * @param sid - The sid
   */
  (sid: string): IpAccessControlListMappingContext;
  /**
   * create a IpAccessControlListMappingInstance
   *
   * @param opts - Options for request
   *
   * @returns Promise that resolves to processed IpAccessControlListMappingInstance
   */
  create(opts: IpAccessControlListMappingListCreateOptions): Promise<IpAccessControlListMappingInstance>;
  /**
   * create a IpAccessControlListMappingInstance
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  create(opts: IpAccessControlListMappingListCreateOptions, callback: (error: Error | null, items: IpAccessControlListMappingInstance) => any): void;
  /**
   * Streams IpAccessControlListMappingInstance records from the API.
   *
   * This operation lazily loads records as efficiently as possible until the limit
   * is reached.
   *
   * The results are passed into the callback function, so this operation is memory efficient.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  each(opts?: IpAccessControlListMappingListEachOptions): void;
  /**
   * Streams IpAccessControlListMappingInstance records from the API.
   *
   * This operation lazily loads records as efficiently as possible until the limit
   * is reached.
   *
   * The results are passed into the callback function, so this operation is memory efficient.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  each(callback: (item: IpAccessControlListMappingInstance, done: (err?: Error) => void) => void): any;
  /**
   * Gets context of a single IpAccessControlListMapping resource
   *
   * @param sid - The sid
   */
  get(sid: string): IpAccessControlListMappingContext;
  /**
   * Retrieve a single target page of IpAccessControlListMappingInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param targetUrl - API-generated URL for the requested results page
   */
  getPage(targetUrl: string): Promise<IpAccessControlListMappingPage>;
  /**
   * Retrieve a single target page of IpAccessControlListMappingInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param targetUrl - API-generated URL for the requested results page
   * @param callback - Callback to handle processed record
   */
  getPage(targetUrl: string, callback: (error: Error | null, items: IpAccessControlListMappingPage) => any): void;
  /**
   * Lists IpAccessControlListMappingInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  list(opts?: IpAccessControlListMappingListOptions): Promise<IpAccessControlListMappingInstance[]>;
  /**
   * Lists IpAccessControlListMappingInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  list(opts: IpAccessControlListMappingListOptions, callback: (error: Error | null, items: IpAccessControlListMappingInstance[]) => any): void;
  /**
   * Lists IpAccessControlListMappingInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  list(callback: (error: Error | null, items: IpAccessControlListMappingInstance[]) => any): void;
  /**
   * Retrieve a single page of IpAccessControlListMappingInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  page(opts?: IpAccessControlListMappingListPageOptions): Promise<IpAccessControlListMappingPage>;
  /**
   * Retrieve a single page of IpAccessControlListMappingInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  page(opts: IpAccessControlListMappingListPageOptions, callback: (error: Error | null, items: IpAccessControlListMappingPage) => any): void;
  /**
   * Retrieve a single page of IpAccessControlListMappingInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  page(callback: (error: Error | null, items: IpAccessControlListMappingPage) => any): void;
}

declare class IpAccessControlListMappingPage extends Page<V2010, IpAccessControlListMappingPayload, IpAccessControlListMappingResource, IpAccessControlListMappingInstance> {
  constructor(version: V2010, response: Response<string>, solution: IpAccessControlListMappingSolution);

  /**
   * Build an instance of IpAccessControlListMappingInstance
   *
   * @param payload - Payload response from the API
   */
  getInstance(payload: IpAccessControlListMappingPayload): IpAccessControlListMappingInstance;
}

declare class IpAccessControlListMappingInstance {
  /**
   * @param version - Version of the resource
   * @param payload - The instance payload
   * @param accountSid - The account_sid
   * @param domainSid - The domain_sid
   * @param sid - The sid
   */
  constructor(version: V2010, payload: IpAccessControlListMappingPayload, accountSid: string, domainSid: string, sid: string);

  private _proxy: IpAccessControlListMappingContext;
  /**
   * The account_sid
   */
  accountSid: string;
  /**
   * The date_created
   */
  dateCreated: Date;
  /**
   * The date_updated
   */
  dateUpdated: Date;
  /**
   * fetch a IpAccessControlListMappingInstance
   *
   * @returns Promise that resolves to processed IpAccessControlListMappingInstance
   */
  fetch(): Promise<IpAccessControlListMappingInstance>;
  /**
   * fetch a IpAccessControlListMappingInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback: (error: Error | null, items: IpAccessControlListMappingInstance) => any): void;
  /**
   * The friendly_name
   */
  friendlyName: string;
  /**
   * remove a IpAccessControlListMappingInstance
   *
   * @returns Promise that resolves to processed IpAccessControlListMappingInstance
   */
  remove(): Promise<IpAccessControlListMappingInstance>;
  /**
   * remove a IpAccessControlListMappingInstance
   *
   * @param callback - Callback to handle processed record
   */
  remove(callback: (error: Error | null, items: IpAccessControlListMappingInstance) => any): void;
  /**
   * The sid
   */
  sid: string;
  /**
   * The subresource_uris
   */
  subresourceUris: string;
  /**
   * The uri
   */
  uri: string;
}

declare class IpAccessControlListMappingContext {
  constructor(version: V2010, accountSid: string, domainSid: string, sid: string);

  /**
   * fetch a IpAccessControlListMappingInstance
   *
   * @returns Promise that resolves to processed IpAccessControlListMappingInstance
   */
  fetch(): Promise<IpAccessControlListMappingInstance>;
  /**
   * fetch a IpAccessControlListMappingInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback: (error: Error | null, items: IpAccessControlListMappingInstance) => any): void;
  /**
   * remove a IpAccessControlListMappingInstance
   *
   * @returns Promise that resolves to processed IpAccessControlListMappingInstance
   */
  remove(): Promise<IpAccessControlListMappingInstance>;
  /**
   * remove a IpAccessControlListMappingInstance
   *
   * @param callback - Callback to handle processed record
   */
  remove(callback: (error: Error | null, items: IpAccessControlListMappingInstance) => any): void;
}

export { IpAccessControlListMappingContext, IpAccessControlListMappingInstance, IpAccessControlListMappingList, IpAccessControlListMappingListCreateOptions, IpAccessControlListMappingListEachOptions, IpAccessControlListMappingListInstance, IpAccessControlListMappingListOptions, IpAccessControlListMappingListPageOptions, IpAccessControlListMappingPage, IpAccessControlListMappingPayload, IpAccessControlListMappingResource, IpAccessControlListMappingSolution }
