/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import { HttpMethod, Url, PhoneNumber, Sid } from './interfaces';

/**
 * <Response> TwiML for Faxes
 */
declare class FaxResponse {
  /**
   * <Response> TwiML for Faxes
   */
  constructor();

  /**
   * <Receive> TwiML Verb
   *
   * @param attributes - TwiML attributes
   */
  receive(attributes?: FaxResponse.ReceiveAttributes): void;
  /**
   * Convert to TwiML
   *
   * @returns TwiML XML
   */
  toString(): any;
}

declare namespace FaxResponse {

  /**
   * Attributes for <Response> TwiML for Faxes
   */
  export interface FaxResponseAttributes {
  }

  /**
   * Attributes for <Receive> TwiML Verb
   */
  export interface ReceiveAttributes {
    /**
     * Receive action URL
     */
    action?: Url;
    /**
     * Receive action URL method
     */
    method?: HttpMethod;
  }

  /**
   * Attributes for <Receive> TwiML Verb
   */
  export interface ReceiveAttributes {
    /**
     * Receive action URL
     */
    action?: Url;
    /**
     * Receive action URL method
     */
    method?: HttpMethod;
  }

}
export = FaxResponse;
