/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />



type HttpMethod = 'get'|'post'|'put'|'patch'|'delete';

type Url = string;

type PhoneNumber = string;

type Sid = string;

export {HttpMethod, Url, PhoneNumber, Sid}
