/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import Version = require('../../base/Version');
import { CredentialList } from './v2/credential';
import { ServiceList } from './v2/service';


/**
 * Initialize the V2 version of Chat
 */
declare class V2 extends Version {
  /**
   * Initialize the V2 version of Chat
   *
   * @param domain - The twilio domain
   */
  constructor(domain: any);

  readonly credentials: CredentialList;
  readonly services: ServiceList;
}

export = V2;
