/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import Domain = require('../base/Domain');
import TwilioClient = require('./Twilio');
import V2010 = require('./api/V2010');


/**
 * Initialize api domain
 */
declare class Api extends Domain {
  /**
   * Initialize api domain
   *
   * @param {Twilio} twilio - The twilio client
   */
  constructor(twilio: TwilioClient);

  readonly account: AccountContext;
  readonly accounts: account;
  readonly addresses: AddressList;
  readonly applications: ApplicationList;
  readonly authorizedConnectApps: AuthorizedConnectAppList;
  readonly availablePhoneNumbers: AvailablePhoneNumberCountryList;
  readonly calls: CallList;
  readonly conferences: ConferenceList;
  readonly connectApps: ConnectAppList;
  readonly incomingPhoneNumbers: IncomingPhoneNumberList;
  readonly keys: KeyList;
  readonly messages: MessageList;
  readonly newKeys: NewKeyList;
  readonly newSigningKeys: NewSigningKeyList;
  readonly notifications: NotificationList;
  readonly outgoingCallerIds: OutgoingCallerIdList;
  readonly queues: QueueList;
  readonly recordings: RecordingList;
  readonly shortCodes: ShortCodeList;
  readonly signingKeys: SigningKeyList;
  readonly sip: SipList;
  readonly tokens: TokenList;
  readonly transcriptions: TranscriptionList;
  readonly usage: UsageList;
  readonly v2010: V2010;
  readonly validationRequests: ValidationRequestList;
}

export {Api}
