/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import Domain = require('../base/Domain');
import TwilioClient = require('./Twilio');
import V1 = require('./lookups/V1');


/**
 * Initialize lookups domain
 */
declare class Lookups extends Domain {
  /**
   * Initialize lookups domain
   *
   * @param {Twilio} twilio - The twilio client
   */
  constructor(twilio: TwilioClient);

  readonly phoneNumbers: phone_number;
  readonly v1: V1;
}

export {Lookups}
