/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import AccSecurity = require('./preview/AccSecurity');
import BulkExports = require('./preview/BulkExports');
import DeployedDevices = require('./preview/DeployedDevices');
import Domain = require('../base/Domain');
import HostedNumbers = require('./preview/HostedNumbers');
import Marketplace = require('./preview/Marketplace');
import Proxy = require('./preview/Proxy');
import Studio = require('./preview/Studio');
import Sync = require('./preview/Sync');
import TwilioClient = require('./Twilio');
import Understand = require('./preview/Understand');
import Wireless = require('./preview/Wireless');


/**
 * Initialize preview domain
 */
declare class Preview extends Domain {
  /**
   * Initialize preview domain
   *
   * @param {Twilio} twilio - The twilio client
   */
  constructor(twilio: TwilioClient);

  readonly acc_security: AccSecurity;
  readonly authorizationDocuments: authorization_document;
  readonly availableAddOns: available_add_on;
  readonly bulk_exports: BulkExports;
  readonly commands: command;
  readonly deployed_devices: DeployedDevices;
  readonly exportConfiguration: export_configuration;
  readonly exports: export;
  readonly fleets: fleet;
  readonly flows: flow;
  readonly hostedNumberOrders: hosted_number_order;
  readonly hosted_numbers: HostedNumbers;
  readonly installedAddOns: installed_add_on;
  readonly marketplace: Marketplace;
  readonly proxy: Proxy;
  readonly ratePlans: rate_plan;
  readonly services: service;
  readonly sims: sim;
  readonly studio: Studio;
  readonly sync: Sync;
  readonly understand: Understand;
  readonly wireless: Wireless;
}

export {Preview}
