/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import Domain = require('../base/Domain');
import TwilioClient = require('./Twilio');
import V1 = require('./taskrouter/V1');


/**
 * Initialize taskrouter domain
 */
declare class Taskrouter extends Domain {
  /**
   * Initialize taskrouter domain
   *
   * @param {Twilio} twilio - The twilio client
   */
  constructor(twilio: TwilioClient);

  readonly v1: V1;
  readonly workspaces: workspace;
}

export {Taskrouter}
