/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import Domain = require('../base/Domain');
import TwilioClient = require('./Twilio');
import V1 = require('./trunking/V1');


/**
 * Initialize trunking domain
 */
declare class Trunking extends Domain {
  /**
   * Initialize trunking domain
   *
   * @param {Twilio} twilio - The twilio client
   */
  constructor(twilio: TwilioClient);

  readonly trunks: trunk;
  readonly v1: V1;
}

export {Trunking}
