/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import Domain = require('../base/Domain');
import TwilioClient = require('./Twilio');
import V1 = require('./wireless/V1');


/**
 * Initialize wireless domain
 */
declare class Wireless extends Domain {
  /**
   * Initialize wireless domain
   *
   * @param {Twilio} twilio - The twilio client
   */
  constructor(twilio: TwilioClient);

  readonly commands: command;
  readonly ratePlans: rate_plan;
  readonly sims: sim;
  readonly v1: V1;
}

export {Wireless}
