/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */

import Page = require('../../../../../base/Page');
import Response = require('../../../../../http/response');
import V1 = require('../../../V1');

declare function TaskQueueCumulativeStatisticsList(version: V1, workspaceSid: string, taskQueueSid: string): TaskQueueCumulativeStatisticsListInstance

interface TaskQueueCumulativeStatisticsResource {
  /**
   * The account_sid
   */
  account_sid: string;
  /**
   * The avg_task_acceptance_time
   */
  avg_task_acceptance_time: number;
  /**
   * The end_time
   */
  end_time: Date;
  /**
   * The reservations_accepted
   */
  reservations_accepted: number;
  /**
   * The reservations_canceled
   */
  reservations_canceled: number;
  /**
   * The reservations_created
   */
  reservations_created: number;
  /**
   * The reservations_rejected
   */
  reservations_rejected: number;
  /**
   * The reservations_rescinded
   */
  reservations_rescinded: number;
  /**
   * The reservations_timed_out
   */
  reservations_timed_out: number;
  /**
   * The split_by_wait_time
   */
  split_by_wait_time: string;
  /**
   * The start_time
   */
  start_time: Date;
  /**
   * The task_queue_sid
   */
  task_queue_sid: string;
  /**
   * The tasks_canceled
   */
  tasks_canceled: number;
  /**
   * The tasks_completed
   */
  tasks_completed: number;
  /**
   * The tasks_deleted
   */
  tasks_deleted: number;
  /**
   * The tasks_entered
   */
  tasks_entered: number;
  /**
   * The tasks_moved
   */
  tasks_moved: number;
  /**
   * The url
   */
  url: string;
  /**
   * The wait_duration_until_accepted
   */
  wait_duration_until_accepted: string;
  /**
   * The wait_duration_until_canceled
   */
  wait_duration_until_canceled: string;
  /**
   * The workspace_sid
   */
  workspace_sid: string;
}

interface TaskQueueCumulativeStatisticsPayload extends TaskQueueCumulativeStatisticsResource, Page.TwilioResponsePayload {
}

interface TaskQueueCumulativeStatisticsSolution {
  taskQueueSid: string;
  workspaceSid: string;
}

interface TaskQueueCumulativeStatisticsListInstance {
  /**
   * Gets context of a single TaskQueueCumulativeStatistics resource
   */
  (): TaskQueueCumulativeStatisticsContext;
  /**
   * Gets context of a single TaskQueueCumulativeStatistics resource
   */
  get(): TaskQueueCumulativeStatisticsContext;
}

interface TaskQueueCumulativeStatisticsListFetchOptions {
  /**
   * The end_date
   */
  endDate?: Date;
  /**
   * The minutes
   */
  minutes?: number;
  /**
   * The split_by_wait_time
   */
  splitByWaitTime?: string;
  /**
   * The start_date
   */
  startDate?: Date;
  /**
   * The task_channel
   */
  taskChannel?: string;
}

interface TaskQueueCumulativeStatisticsListFetchOptions {
  /**
   * The end_date
   */
  endDate?: Date;
  /**
   * The minutes
   */
  minutes?: number;
  /**
   * The split_by_wait_time
   */
  splitByWaitTime?: string;
  /**
   * The start_date
   */
  startDate?: Date;
  /**
   * The task_channel
   */
  taskChannel?: string;
}

declare class TaskQueueCumulativeStatisticsPage extends Page<V1, TaskQueueCumulativeStatisticsPayload, TaskQueueCumulativeStatisticsResource, TaskQueueCumulativeStatisticsInstance> {
  constructor(version: V1, response: Response<string>, solution: TaskQueueCumulativeStatisticsSolution);

  /**
   * Build an instance of TaskQueueCumulativeStatisticsInstance
   *
   * @param payload - Payload response from the API
   */
  getInstance(payload: TaskQueueCumulativeStatisticsPayload): TaskQueueCumulativeStatisticsInstance;
}

declare class TaskQueueCumulativeStatisticsInstance {
  /**
   * @param version - Version of the resource
   * @param payload - The instance payload
   * @param workspaceSid - The workspace_sid
   * @param taskQueueSid - The task_queue_sid
   */
  constructor(version: V1, payload: TaskQueueCumulativeStatisticsPayload, workspaceSid: string, taskQueueSid: string);

  private _proxy: TaskQueueCumulativeStatisticsContext;
  /**
   * The account_sid
   */
  accountSid: string;
  /**
   * The avg_task_acceptance_time
   */
  avgTaskAcceptanceTime: number;
  /**
   * The end_time
   */
  endTime: Date;
  /**
   * fetch a TaskQueueCumulativeStatisticsInstance
   *
   * @param opts - Options for request
   *
   * @returns Promise that resolves to processed TaskQueueCumulativeStatisticsInstance
   */
  fetch(opts?: TaskQueueCumulativeStatisticsListFetchOptions): Promise<TaskQueueCumulativeStatisticsInstance>;
  /**
   * fetch a TaskQueueCumulativeStatisticsInstance
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  fetch(opts: TaskQueueCumulativeStatisticsListFetchOptions, callback: (error: Error | null, items: TaskQueueCumulativeStatisticsInstance) => any): void;
  /**
   * fetch a TaskQueueCumulativeStatisticsInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback: (error: Error | null, items: TaskQueueCumulativeStatisticsInstance) => any): void;
  /**
   * The reservations_accepted
   */
  reservationsAccepted: number;
  /**
   * The reservations_canceled
   */
  reservationsCanceled: number;
  /**
   * The reservations_created
   */
  reservationsCreated: number;
  /**
   * The reservations_rejected
   */
  reservationsRejected: number;
  /**
   * The reservations_rescinded
   */
  reservationsRescinded: number;
  /**
   * The reservations_timed_out
   */
  reservationsTimedOut: number;
  /**
   * The split_by_wait_time
   */
  splitByWaitTime: string;
  /**
   * The start_time
   */
  startTime: Date;
  /**
   * The task_queue_sid
   */
  taskQueueSid: string;
  /**
   * The tasks_canceled
   */
  tasksCanceled: number;
  /**
   * The tasks_completed
   */
  tasksCompleted: number;
  /**
   * The tasks_deleted
   */
  tasksDeleted: number;
  /**
   * The tasks_entered
   */
  tasksEntered: number;
  /**
   * The tasks_moved
   */
  tasksMoved: number;
  /**
   * The url
   */
  url: string;
  /**
   * The wait_duration_until_accepted
   */
  waitDurationUntilAccepted: string;
  /**
   * The wait_duration_until_canceled
   */
  waitDurationUntilCanceled: string;
  /**
   * The workspace_sid
   */
  workspaceSid: string;
}

declare class TaskQueueCumulativeStatisticsContext {
  constructor(version: V1, workspaceSid: string, taskQueueSid: string);

  /**
   * fetch a TaskQueueCumulativeStatisticsInstance
   *
   * @param opts - Options for request
   *
   * @returns Promise that resolves to processed TaskQueueCumulativeStatisticsInstance
   */
  fetch(opts?: TaskQueueCumulativeStatisticsListFetchOptions): Promise<TaskQueueCumulativeStatisticsInstance>;
  /**
   * fetch a TaskQueueCumulativeStatisticsInstance
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  fetch(opts: TaskQueueCumulativeStatisticsListFetchOptions, callback: (error: Error | null, items: TaskQueueCumulativeStatisticsInstance) => any): void;
  /**
   * fetch a TaskQueueCumulativeStatisticsInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback: (error: Error | null, items: TaskQueueCumulativeStatisticsInstance) => any): void;
}

export {TaskQueueCumulativeStatisticsSolution, TaskQueueCumulativeStatisticsInstance, TaskQueueCumulativeStatisticsResource, TaskQueueCumulativeStatisticsList, TaskQueueCumulativeStatisticsContext, TaskQueueCumulativeStatisticsListFetchOptions, TaskQueueCumulativeStatisticsListInstance, TaskQueueCumulativeStatisticsPayload, TaskQueueCumulativeStatisticsPage}
