/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */

import Page = require('../../../../../base/Page');
import Response = require('../../../../../http/response');
import V1 = require('../../../V1');

declare function TaskQueueRealTimeStatisticsList(version: V1, workspaceSid: string, taskQueueSid: string): TaskQueueRealTimeStatisticsListInstance

interface TaskQueueRealTimeStatisticsResource {
  /**
   * The account_sid
   */
  account_sid: string;
  /**
   * The activity_statistics
   */
  activity_statistics: string;
  /**
   * The longest_task_waiting_age
   */
  longest_task_waiting_age: number;
  /**
   * The task_queue_sid
   */
  task_queue_sid: string;
  /**
   * The tasks_by_priority
   */
  tasks_by_priority: string;
  /**
   * The tasks_by_status
   */
  tasks_by_status: string;
  /**
   * The total_available_workers
   */
  total_available_workers: number;
  /**
   * The total_eligible_workers
   */
  total_eligible_workers: number;
  /**
   * The total_tasks
   */
  total_tasks: number;
  /**
   * The url
   */
  url: string;
  /**
   * The workspace_sid
   */
  workspace_sid: string;
}

interface TaskQueueRealTimeStatisticsPayload extends TaskQueueRealTimeStatisticsResource, Page.TwilioResponsePayload {
}

interface TaskQueueRealTimeStatisticsSolution {
  taskQueueSid: string;
  workspaceSid: string;
}

interface TaskQueueRealTimeStatisticsListInstance {
  /**
   * Gets context of a single TaskQueueRealTimeStatistics resource
   */
  (): TaskQueueRealTimeStatisticsContext;
  /**
   * Gets context of a single TaskQueueRealTimeStatistics resource
   */
  get(): TaskQueueRealTimeStatisticsContext;
}

interface TaskQueueRealTimeStatisticsListFetchOptions {
  /**
   * The task_channel
   */
  taskChannel?: string;
}

interface TaskQueueRealTimeStatisticsListFetchOptions {
  /**
   * The task_channel
   */
  taskChannel?: string;
}

declare class TaskQueueRealTimeStatisticsPage extends Page<V1, TaskQueueRealTimeStatisticsPayload, TaskQueueRealTimeStatisticsResource, TaskQueueRealTimeStatisticsInstance> {
  constructor(version: V1, response: Response<string>, solution: TaskQueueRealTimeStatisticsSolution);

  /**
   * Build an instance of TaskQueueRealTimeStatisticsInstance
   *
   * @param payload - Payload response from the API
   */
  getInstance(payload: TaskQueueRealTimeStatisticsPayload): TaskQueueRealTimeStatisticsInstance;
}

declare class TaskQueueRealTimeStatisticsInstance {
  /**
   * @param version - Version of the resource
   * @param payload - The instance payload
   * @param workspaceSid - The workspace_sid
   * @param taskQueueSid - The task_queue_sid
   */
  constructor(version: V1, payload: TaskQueueRealTimeStatisticsPayload, workspaceSid: string, taskQueueSid: string);

  private _proxy: TaskQueueRealTimeStatisticsContext;
  /**
   * The account_sid
   */
  accountSid: string;
  /**
   * The activity_statistics
   */
  activityStatistics: string;
  /**
   * fetch a TaskQueueRealTimeStatisticsInstance
   *
   * @param opts - Options for request
   *
   * @returns Promise that resolves to processed TaskQueueRealTimeStatisticsInstance
   */
  fetch(opts?: TaskQueueRealTimeStatisticsListFetchOptions): Promise<TaskQueueRealTimeStatisticsInstance>;
  /**
   * fetch a TaskQueueRealTimeStatisticsInstance
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  fetch(opts: TaskQueueRealTimeStatisticsListFetchOptions, callback: (error: Error | null, items: TaskQueueRealTimeStatisticsInstance) => any): void;
  /**
   * fetch a TaskQueueRealTimeStatisticsInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback: (error: Error | null, items: TaskQueueRealTimeStatisticsInstance) => any): void;
  /**
   * The longest_task_waiting_age
   */
  longestTaskWaitingAge: number;
  /**
   * The task_queue_sid
   */
  taskQueueSid: string;
  /**
   * The tasks_by_priority
   */
  tasksByPriority: string;
  /**
   * The tasks_by_status
   */
  tasksByStatus: string;
  /**
   * The total_available_workers
   */
  totalAvailableWorkers: number;
  /**
   * The total_eligible_workers
   */
  totalEligibleWorkers: number;
  /**
   * The total_tasks
   */
  totalTasks: number;
  /**
   * The url
   */
  url: string;
  /**
   * The workspace_sid
   */
  workspaceSid: string;
}

declare class TaskQueueRealTimeStatisticsContext {
  constructor(version: V1, workspaceSid: string, taskQueueSid: string);

  /**
   * fetch a TaskQueueRealTimeStatisticsInstance
   *
   * @param opts - Options for request
   *
   * @returns Promise that resolves to processed TaskQueueRealTimeStatisticsInstance
   */
  fetch(opts?: TaskQueueRealTimeStatisticsListFetchOptions): Promise<TaskQueueRealTimeStatisticsInstance>;
  /**
   * fetch a TaskQueueRealTimeStatisticsInstance
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  fetch(opts: TaskQueueRealTimeStatisticsListFetchOptions, callback: (error: Error | null, items: TaskQueueRealTimeStatisticsInstance) => any): void;
  /**
   * fetch a TaskQueueRealTimeStatisticsInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback: (error: Error | null, items: TaskQueueRealTimeStatisticsInstance) => any): void;
}

export {TaskQueueRealTimeStatisticsListFetchOptions, TaskQueueRealTimeStatisticsPage, TaskQueueRealTimeStatisticsContext, TaskQueueRealTimeStatisticsListInstance, TaskQueueRealTimeStatisticsList, TaskQueueRealTimeStatisticsResource, TaskQueueRealTimeStatisticsSolution, TaskQueueRealTimeStatisticsPayload, TaskQueueRealTimeStatisticsInstance}
