/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */

import Page = require('../../../../../base/Page');
import Response = require('../../../../../http/response');
import V2010 = require('../../../V2010');
import { ListEachOptions, ListOptions, PageOptions } from '../../../../../interfaces';

declare function RecordingList(version: V2010, accountSid: string, callSid: string): RecordingListInstance

type RecordingStatus = 'in-progress'|'paused'|'stopped'|'processing'|'completed'|'failed';

type RecordingSource = 'DialVerb'|'Conference'|'OutboundAPI'|'Trunking'|'RecordVerb'|'StartCallRecordingAPI'|'StartConferenceRecordingAPI';

interface RecordingResource {
  /**
   * The account_sid
   */
  account_sid: string;
  /**
   * The api_version
   */
  api_version: string;
  /**
   * The call_sid
   */
  call_sid: string;
  /**
   * The channels
   */
  channels: number;
  /**
   * The date_created
   */
  date_created: Date;
  /**
   * The date_updated
   */
  date_updated: Date;
  /**
   * The duration
   */
  duration: string;
  /**
   * The encryption_details
   */
  encryption_details: string;
  /**
   * The error_code
   */
  error_code: number;
  /**
   * The price
   */
  price: number;
  /**
   * The price_unit
   */
  price_unit: string;
  /**
   * The sid
   */
  sid: string;
  /**
   * The source
   */
  source: RecordingSource;
  /**
   * The status
   */
  status: RecordingStatus;
  /**
   * The uri
   */
  uri: string;
}

interface RecordingPayload extends RecordingResource, Page.TwilioResponsePayload {
}

interface RecordingSolution {
  accountSid: string;
  callSid: string;
}

interface RecordingListEachOptions extends ListEachOptions<RecordingInstance> {
  /**
   * The date_created
   */
  dateCreated?: Date;
}

interface RecordingListOptions extends ListOptions<RecordingInstance> {
  /**
   * The date_created
   */
  dateCreated?: Date;
}

interface RecordingListPageOptions extends PageOptions<RecordingPage> {
  /**
   * The date_created
   */
  dateCreated?: Date;
}

interface RecordingListInstance {
  /**
   * Gets context of a single Recording resource
   *
   * @param sid - The sid
   */
  (sid: string): RecordingContext;
  /**
   * Streams RecordingInstance records from the API.
   *
   * This operation lazily loads records as efficiently as possible until the limit
   * is reached.
   *
   * The results are passed into the callback function, so this operation is memory efficient.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  each(opts?: RecordingListEachOptions): void;
  /**
   * Streams RecordingInstance records from the API.
   *
   * This operation lazily loads records as efficiently as possible until the limit
   * is reached.
   *
   * The results are passed into the callback function, so this operation is memory efficient.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  each(callback: (item: RecordingInstance, done: (err?: Error) => void) => void): any;
  /**
   * Gets context of a single Recording resource
   *
   * @param sid - The sid
   */
  get(sid: string): RecordingContext;
  /**
   * Retrieve a single target page of RecordingInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param targetUrl - API-generated URL for the requested results page
   */
  getPage(targetUrl: string): Promise<RecordingPage>;
  /**
   * Retrieve a single target page of RecordingInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param targetUrl - API-generated URL for the requested results page
   * @param callback - Callback to handle processed record
   */
  getPage(targetUrl: string, callback: (error: Error | null, items: RecordingPage) => any): void;
  /**
   * Lists RecordingInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  list(opts?: RecordingListOptions): Promise<RecordingInstance[]>;
  /**
   * Lists RecordingInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  list(opts: RecordingListOptions, callback: (error: Error | null, items: RecordingInstance[]) => any): void;
  /**
   * Lists RecordingInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  list(callback: (error: Error | null, items: RecordingInstance[]) => any): void;
  /**
   * Retrieve a single page of RecordingInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  page(opts?: RecordingListPageOptions): Promise<RecordingPage>;
  /**
   * Retrieve a single page of RecordingInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  page(opts: RecordingListPageOptions, callback: (error: Error | null, items: RecordingPage) => any): void;
  /**
   * Retrieve a single page of RecordingInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  page(callback: (error: Error | null, items: RecordingPage) => any): void;
}

declare class RecordingPage extends Page<V2010, RecordingPayload, RecordingResource, RecordingInstance> {
  constructor(version: V2010, response: Response<string>, solution: RecordingSolution);

  /**
   * Build an instance of RecordingInstance
   *
   * @param payload - Payload response from the API
   */
  getInstance(payload: RecordingPayload): RecordingInstance;
}

declare class RecordingInstance {
  /**
   * @param version - Version of the resource
   * @param payload - The instance payload
   * @param accountSid - The account_sid
   * @param callSid - The call_sid
   * @param sid - The sid
   */
  constructor(version: V2010, payload: RecordingPayload, accountSid: string, callSid: string, sid: string);

  private _proxy: RecordingContext;
  /**
   * The account_sid
   */
  accountSid: string;
  /**
   * The api_version
   */
  apiVersion: string;
  /**
   * The call_sid
   */
  callSid: string;
  /**
   * The channels
   */
  channels: number;
  /**
   * The date_created
   */
  dateCreated: Date;
  /**
   * The date_updated
   */
  dateUpdated: Date;
  /**
   * The duration
   */
  duration: string;
  /**
   * The encryption_details
   */
  encryptionDetails: string;
  /**
   * The error_code
   */
  errorCode: number;
  /**
   * fetch a RecordingInstance
   *
   * @returns Promise that resolves to processed RecordingInstance
   */
  fetch(): Promise<RecordingInstance>;
  /**
   * fetch a RecordingInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback: (error: Error | null, items: RecordingInstance) => any): void;
  /**
   * The price
   */
  price: number;
  /**
   * The price_unit
   */
  priceUnit: string;
  /**
   * remove a RecordingInstance
   *
   * @returns Promise that resolves to processed RecordingInstance
   */
  remove(): Promise<RecordingInstance>;
  /**
   * remove a RecordingInstance
   *
   * @param callback - Callback to handle processed record
   */
  remove(callback: (error: Error | null, items: RecordingInstance) => any): void;
  /**
   * The sid
   */
  sid: string;
  /**
   * The source
   */
  source: RecordingSource;
  /**
   * The status
   */
  status: RecordingStatus;
  /**
   * The uri
   */
  uri: string;
}

declare class RecordingContext {
  constructor(version: V2010, accountSid: string, callSid: string, sid: string);

  /**
   * fetch a RecordingInstance
   *
   * @returns Promise that resolves to processed RecordingInstance
   */
  fetch(): Promise<RecordingInstance>;
  /**
   * fetch a RecordingInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback: (error: Error | null, items: RecordingInstance) => any): void;
  /**
   * remove a RecordingInstance
   *
   * @returns Promise that resolves to processed RecordingInstance
   */
  remove(): Promise<RecordingInstance>;
  /**
   * remove a RecordingInstance
   *
   * @param callback - Callback to handle processed record
   */
  remove(callback: (error: Error | null, items: RecordingInstance) => any): void;
}

export {RecordingResource, RecordingPayload, RecordingContext, RecordingList, RecordingListInstance, RecordingListOptions, RecordingSource, RecordingPage, RecordingInstance, RecordingStatus, RecordingListPageOptions, RecordingSolution, RecordingListEachOptions}
