/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
<<<<<<< HEAD

import Version = require('../../base/Version');
import { FaxListInstance } from './v1/fax';
=======
/// <reference types="node" />

import Version = require('../../base/Version');
import { FaxList } from './v1/fax';
>>>>>>> Initial typescript definitions


/**
 * Initialize the V1 version of Fax
 */
declare class V1 extends Version {
  /**
   * Initialize the V1 version of Fax
   *
   * @param domain - The twilio domain
   */
  constructor(domain: any);

<<<<<<< HEAD
  readonly faxes: FaxListInstance;
=======
  readonly faxes: FaxList;
>>>>>>> Initial typescript definitions
}

export = V1;
