/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */

import Page = require('../../../../base/Page');
import Response = require('../../../../http/response');
import V1 = require('../../V1');

declare function NumberList(version: V1): NumberListInstance

interface NumberResource {
  /**
   * The country
   */
  country: string;
  /**
   * The inbound_call_price
   */
  inbound_call_price: string;
  /**
   * The iso_country
   */
  iso_country: string;
  /**
   * The number
   */
  number: string;
  /**
   * The outbound_call_price
   */
  outbound_call_price: string;
  /**
   * The price_unit
   */
  price_unit: string;
  /**
   * The url
   */
  url: string;
}

interface NumberPayload extends NumberResource, Page.TwilioResponsePayload {
}

interface NumberSolution {
}

interface NumberListInstance {
  /**
   * Gets context of a single Number resource
   *
   * @param number - The number
   */
  (number: string): NumberContext;
  /**
   * Gets context of a single Number resource
   *
   * @param number - The number
   */
  get(number: string): NumberContext;
}

declare class NumberPage extends Page<V1, NumberPayload, NumberResource, NumberInstance> {
  constructor(version: V1, response: Response<string>, solution: NumberSolution);

  /**
   * Build an instance of NumberInstance
   *
   * @param payload - Payload response from the API
   */
  getInstance(payload: NumberPayload): NumberInstance;
}

declare class NumberInstance {
  /**
   * @param version - Version of the resource
   * @param payload - The instance payload
   * @param number - The number
   */
  constructor(version: V1, payload: NumberPayload, number: string);

  private _proxy: NumberContext;
  /**
   * The country
   */
  country: string;
  /**
   * fetch a NumberInstance
   *
   * @returns Promise that resolves to processed NumberInstance
   */
  fetch(): Promise<NumberInstance>;
  /**
   * fetch a NumberInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback: (error: Error | null, items: NumberInstance) => any): void;
  /**
   * The inbound_call_price
   */
  inboundCallPrice: string;
  /**
   * The iso_country
   */
  isoCountry: string;
  /**
   * The number
   */
  number: string;
  /**
   * The outbound_call_price
   */
  outboundCallPrice: string;
  /**
   * The price_unit
   */
  priceUnit: string;
  /**
   * The url
   */
  url: string;
}

declare class NumberContext {
  constructor(version: V1, number: string);

  /**
   * fetch a NumberInstance
   *
   * @returns Promise that resolves to processed NumberInstance
   */
  fetch(): Promise<NumberInstance>;
  /**
   * fetch a NumberInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback: (error: Error | null, items: NumberInstance) => any): void;
}

export {NumberListInstance, NumberPayload, NumberInstance, NumberContext, NumberList, NumberSolution, NumberPage, NumberResource}
