/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */

import Page = require('../../../../../base/Page');
import Response = require('../../../../../http/response');
import V2 = require('../../../V2');
import { ListEachOptions, ListOptions, PageOptions } from '../../../../../interfaces';

declare function MemberList(version: V2, serviceSid: string, channelSid: string): MemberListInstance

interface MemberResource {
  /**
   * The account_sid
   */
  account_sid: string;
  /**
   * The channel_sid
   */
  channel_sid: string;
  /**
   * The date_created
   */
  date_created: Date;
  /**
   * The date_updated
   */
  date_updated: Date;
  /**
   * The identity
   */
  identity: string;
  /**
   * The last_consumed_message_index
   */
  last_consumed_message_index: number;
  /**
   * The last_consumption_timestamp
   */
  last_consumption_timestamp: Date;
  /**
   * The role_sid
   */
  role_sid: string;
  /**
   * The service_sid
   */
  service_sid: string;
  /**
   * The sid
   */
  sid: string;
  /**
   * The url
   */
  url: string;
}

interface MemberPayload extends MemberResource, Page.TwilioResponsePayload {
}

interface MemberSolution {
  channelSid: string;
  serviceSid: string;
}

interface MemberListCreateOptions {
  /**
   * The date_created
   */
  dateCreated?: Date;
  /**
   * The date_updated
   */
  dateUpdated?: Date;
  /**
   * The identity
   */
  identity: string;
  /**
   * The last_consumed_message_index
   */
  lastConsumedMessageIndex?: number;
  /**
   * The last_consumption_timestamp
   */
  lastConsumptionTimestamp?: Date;
  /**
   * The role_sid
   */
  roleSid?: string;
}

interface MemberListEachOptions extends ListEachOptions<MemberInstance> {
  /**
   * The identity
   */
  identity?: string[];
}

interface MemberListOptions extends ListOptions<MemberInstance> {
  /**
   * The identity
   */
  identity?: string[];
}

interface MemberListPageOptions extends PageOptions<MemberPage> {
  /**
   * The identity
   */
  identity?: string[];
}

interface MemberListInstance {
  /**
   * Gets context of a single Member resource
   *
   * @param sid - The sid
   */
  (sid: string): MemberContext;
  /**
   * create a MemberInstance
   *
   * @param opts - Options for request
   *
   * @returns Promise that resolves to processed MemberInstance
   */
  create(opts: MemberListCreateOptions): Promise<MemberInstance>;
  /**
   * create a MemberInstance
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  create(opts: MemberListCreateOptions, callback: (error: Error | null, items: MemberInstance) => any): void;
  /**
   * Streams MemberInstance records from the API.
   *
   * This operation lazily loads records as efficiently as possible until the limit
   * is reached.
   *
   * The results are passed into the callback function, so this operation is memory efficient.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  each(opts?: MemberListEachOptions): void;
  /**
   * Streams MemberInstance records from the API.
   *
   * This operation lazily loads records as efficiently as possible until the limit
   * is reached.
   *
   * The results are passed into the callback function, so this operation is memory efficient.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  each(callback: (item: MemberInstance, done: (err?: Error) => void) => void): any;
  /**
   * Gets context of a single Member resource
   *
   * @param sid - The sid
   */
  get(sid: string): MemberContext;
  /**
   * Retrieve a single target page of MemberInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param targetUrl - API-generated URL for the requested results page
   */
  getPage(targetUrl: string): Promise<MemberPage>;
  /**
   * Retrieve a single target page of MemberInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param targetUrl - API-generated URL for the requested results page
   * @param callback - Callback to handle processed record
   */
  getPage(targetUrl: string, callback: (error: Error | null, items: MemberPage) => any): void;
  /**
   * Lists MemberInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  list(opts?: MemberListOptions): Promise<MemberInstance[]>;
  /**
   * Lists MemberInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  list(opts: MemberListOptions, callback: (error: Error | null, items: MemberInstance[]) => any): void;
  /**
   * Lists MemberInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  list(callback: (error: Error | null, items: MemberInstance[]) => any): void;
  /**
   * Retrieve a single page of MemberInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  page(opts?: MemberListPageOptions): Promise<MemberPage>;
  /**
   * Retrieve a single page of MemberInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  page(opts: MemberListPageOptions, callback: (error: Error | null, items: MemberPage) => any): void;
  /**
   * Retrieve a single page of MemberInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  page(callback: (error: Error | null, items: MemberPage) => any): void;
}

interface MemberListFetchOptions {
  /**
   * The date_created
   */
  dateCreated?: Date;
  /**
   * The date_updated
   */
  dateUpdated?: Date;
  /**
   * The last_consumed_message_index
   */
  lastConsumedMessageIndex?: number;
  /**
   * The last_consumption_timestamp
   */
  lastConsumptionTimestamp?: Date;
  /**
   * The role_sid
   */
  roleSid?: string;
}

interface MemberListFetchOptions {
  /**
   * The date_created
   */
  dateCreated?: Date;
  /**
   * The date_updated
   */
  dateUpdated?: Date;
  /**
   * The last_consumed_message_index
   */
  lastConsumedMessageIndex?: number;
  /**
   * The last_consumption_timestamp
   */
  lastConsumptionTimestamp?: Date;
  /**
   * The role_sid
   */
  roleSid?: string;
}

declare class MemberPage extends Page<V2, MemberPayload, MemberResource, MemberInstance> {
  constructor(version: V2, response: Response<string>, solution: MemberSolution);

  /**
   * Build an instance of MemberInstance
   *
   * @param payload - Payload response from the API
   */
  getInstance(payload: MemberPayload): MemberInstance;
}

declare class MemberInstance {
  /**
   * @param version - Version of the resource
   * @param payload - The instance payload
   * @param serviceSid - The service_sid
   * @param channelSid - The channel_sid
   * @param sid - The sid
   */
  constructor(version: V2, payload: MemberPayload, serviceSid: string, channelSid: string, sid: string);

  private _proxy: MemberContext;
  /**
   * The account_sid
   */
  accountSid: string;
  /**
   * The channel_sid
   */
  channelSid: string;
  /**
   * The date_created
   */
  dateCreated: Date;
  /**
   * The date_updated
   */
  dateUpdated: Date;
  /**
   * fetch a MemberInstance
   *
   * @returns Promise that resolves to processed MemberInstance
   */
  fetch(): Promise<MemberInstance>;
  /**
   * fetch a MemberInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback: (error: Error | null, items: MemberInstance) => any): void;
  /**
   * The identity
   */
  identity: string;
  /**
   * The last_consumed_message_index
   */
  lastConsumedMessageIndex: number;
  /**
   * The last_consumption_timestamp
   */
  lastConsumptionTimestamp: Date;
  /**
   * remove a MemberInstance
   *
   * @returns Promise that resolves to processed MemberInstance
   */
  remove(): Promise<MemberInstance>;
  /**
   * remove a MemberInstance
   *
   * @param callback - Callback to handle processed record
   */
  remove(callback: (error: Error | null, items: MemberInstance) => any): void;
  /**
   * The role_sid
   */
  roleSid: string;
  /**
   * The service_sid
   */
  serviceSid: string;
  /**
   * The sid
   */
  sid: string;
  /**
   * update a MemberInstance
   *
   * @param opts - Options for request
   *
   * @returns Promise that resolves to processed MemberInstance
   */
  update(opts?: MemberListFetchOptions): Promise<MemberInstance>;
  /**
   * update a MemberInstance
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  update(opts: MemberListFetchOptions, callback: (error: Error | null, items: MemberInstance) => any): void;
  /**
   * update a MemberInstance
   *
   * @param callback - Callback to handle processed record
   */
  update(callback: (error: Error | null, items: MemberInstance) => any): void;
  /**
   * The url
   */
  url: string;
}

declare class MemberContext {
  constructor(version: V2, serviceSid: string, channelSid: string, sid: string);

  /**
   * fetch a MemberInstance
   *
   * @returns Promise that resolves to processed MemberInstance
   */
  fetch(): Promise<MemberInstance>;
  /**
   * fetch a MemberInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback: (error: Error | null, items: MemberInstance) => any): void;
  /**
   * remove a MemberInstance
   *
   * @returns Promise that resolves to processed MemberInstance
   */
  remove(): Promise<MemberInstance>;
  /**
   * remove a MemberInstance
   *
   * @param callback - Callback to handle processed record
   */
  remove(callback: (error: Error | null, items: MemberInstance) => any): void;
  /**
   * update a MemberInstance
   *
   * @param opts - Options for request
   *
   * @returns Promise that resolves to processed MemberInstance
   */
  update(opts?: MemberListFetchOptions): Promise<MemberInstance>;
  /**
   * update a MemberInstance
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  update(opts: MemberListFetchOptions, callback: (error: Error | null, items: MemberInstance) => any): void;
  /**
   * update a MemberInstance
   *
   * @param callback - Callback to handle processed record
   */
  update(callback: (error: Error | null, items: MemberInstance) => any): void;
}

export {MemberPage, MemberInstance, MemberContext, MemberListInstance, MemberListPageOptions, MemberListOptions, MemberResource, MemberSolution, MemberListFetchOptions, MemberPayload, MemberListCreateOptions, MemberList, MemberListEachOptions}
