/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import Version = require('../../base/Version');
import { AccountContext } from './v2010/account';
import { AccountList } from './v2010/account';


/**
 * Initialize the V2010 version of Api
 */
declare class V2010 extends Version {
  /**
   * Initialize the V2010 version of Api
   *
   * @param domain - The twilio domain
   */
  constructor(domain: any);

  account: AccountContext;
  readonly accounts: AccountList;
  readonly addresses: AddressList;
  readonly applications: ApplicationList;
  readonly authorizedConnectApps: AuthorizedConnectAppList;
  readonly availablePhoneNumbers: AvailablePhoneNumberCountryList;
  readonly calls: CallList;
  readonly conferences: ConferenceList;
  readonly connectApps: ConnectAppList;
  readonly incomingPhoneNumbers: IncomingPhoneNumberList;
  readonly keys: KeyList;
  readonly messages: MessageList;
  readonly newKeys: NewKeyList;
  readonly newSigningKeys: NewSigningKeyList;
  readonly notifications: NotificationList;
  readonly outgoingCallerIds: OutgoingCallerIdList;
  readonly queues: QueueList;
  readonly recordings: RecordingList;
  readonly shortCodes: ShortCodeList;
  readonly signingKeys: SigningKeyList;
  readonly sip: SipList;
  readonly tokens: TokenList;
  readonly transcriptions: TranscriptionList;
  readonly usage: UsageList;
  readonly validationRequests: ValidationRequestList;
}

export = V2010;
