/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */

import Page = require('../../../../../base/Page');
import Response = require('../../../../../http/response');
import V2010 = require('../../../V2010');
import { ListEachOptions, ListOptions, PageOptions } from '../../../../../interfaces';

declare function LocalList(version: V2010, accountSid: string): LocalListInstance

type LocalAddressRequirement = 'none'|'any'|'local'|'foreign';

interface LocalResource {
  /**
   * The account_sid
   */
  account_sid: string;
  /**
   * The address_requirements
   */
  address_requirements: LocalAddressRequirement;
  /**
   * The address_sid
   */
  address_sid: string;
  /**
   * The api_version
   */
  api_version: string;
  /**
   * The beta
   */
  beta: boolean;
  /**
   * The capabilities
   */
  capabilities: string;
  /**
   * The date_created
   */
  date_created: Date;
  /**
   * The date_updated
   */
  date_updated: Date;
  /**
   * The friendly_name
   */
  friendly_name: string;
  /**
   * The identity_sid
   */
  identity_sid: string;
  /**
   * The origin
   */
  origin: string;
  /**
   * The phone_number
   */
  phone_number: string;
  /**
   * The sid
   */
  sid: string;
  /**
   * The sms_application_sid
   */
  sms_application_sid: string;
  /**
   * The sms_fallback_method
   */
  sms_fallback_method: string;
  /**
   * The sms_fallback_url
   */
  sms_fallback_url: string;
  /**
   * The sms_method
   */
  sms_method: string;
  /**
   * The sms_url
   */
  sms_url: string;
  /**
   * The status_callback
   */
  status_callback: string;
  /**
   * The status_callback_method
   */
  status_callback_method: string;
  /**
   * The trunk_sid
   */
  trunk_sid: string;
  /**
   * The uri
   */
  uri: string;
  /**
   * The voice_application_sid
   */
  voice_application_sid: string;
  /**
   * The voice_caller_id_lookup
   */
  voice_caller_id_lookup: boolean;
  /**
   * The voice_fallback_method
   */
  voice_fallback_method: string;
  /**
   * The voice_fallback_url
   */
  voice_fallback_url: string;
  /**
   * The voice_method
   */
  voice_method: string;
  /**
   * The voice_url
   */
  voice_url: string;
}

interface LocalPayload extends LocalResource, Page.TwilioResponsePayload {
}

interface LocalSolution {
  accountSid: string;
}

interface LocalListEachOptions extends ListEachOptions<LocalInstance> {
  /**
   * The beta
   */
  beta?: boolean;
  /**
   * The friendly_name
   */
  friendlyName?: string;
  /**
   * The origin
   */
  origin?: string;
  /**
   * The phone_number
   */
  phoneNumber?: string;
}

interface LocalListOptions extends ListOptions<LocalInstance> {
  /**
   * The beta
   */
  beta?: boolean;
  /**
   * The friendly_name
   */
  friendlyName?: string;
  /**
   * The origin
   */
  origin?: string;
  /**
   * The phone_number
   */
  phoneNumber?: string;
}

interface LocalListPageOptions extends PageOptions<LocalPage> {
  /**
   * The beta
   */
  beta?: boolean;
  /**
   * The friendly_name
   */
  friendlyName?: string;
  /**
   * The origin
   */
  origin?: string;
  /**
   * The phone_number
   */
  phoneNumber?: string;
}

interface LocalListCreateOptions {
  /**
   * The address_sid
   */
  addressSid?: string;
  /**
   * The api_version
   */
  apiVersion?: string;
  /**
   * The friendly_name
   */
  friendlyName?: string;
  /**
   * The identity_sid
   */
  identitySid?: string;
  /**
   * The phone_number
   */
  phoneNumber: string;
  /**
   * The sms_application_sid
   */
  smsApplicationSid?: string;
  /**
   * The sms_fallback_method
   */
  smsFallbackMethod?: string;
  /**
   * The sms_fallback_url
   */
  smsFallbackUrl?: string;
  /**
   * The sms_method
   */
  smsMethod?: string;
  /**
   * The sms_url
   */
  smsUrl?: string;
  /**
   * The status_callback
   */
  statusCallback?: string;
  /**
   * The status_callback_method
   */
  statusCallbackMethod?: string;
  /**
   * The voice_application_sid
   */
  voiceApplicationSid?: string;
  /**
   * The voice_caller_id_lookup
   */
  voiceCallerIdLookup?: boolean;
  /**
   * The voice_fallback_method
   */
  voiceFallbackMethod?: string;
  /**
   * The voice_fallback_url
   */
  voiceFallbackUrl?: string;
  /**
   * The voice_method
   */
  voiceMethod?: string;
  /**
   * The voice_url
   */
  voiceUrl?: string;
}

interface LocalListInstance {
  /**
   * create a LocalInstance
   *
   * @param opts - Options for request
   *
   * @returns Promise that resolves to processed LocalInstance
   */
  create(opts: LocalListCreateOptions): Promise<LocalInstance>;
  /**
   * create a LocalInstance
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  create(opts: LocalListCreateOptions, callback: (error: Error | null, items: LocalInstance) => any): void;
  /**
   * Streams LocalInstance records from the API.
   *
   * This operation lazily loads records as efficiently as possible until the limit
   * is reached.
   *
   * The results are passed into the callback function, so this operation is memory efficient.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  each(opts?: LocalListEachOptions): void;
  /**
   * Streams LocalInstance records from the API.
   *
   * This operation lazily loads records as efficiently as possible until the limit
   * is reached.
   *
   * The results are passed into the callback function, so this operation is memory efficient.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  each(callback: (item: LocalInstance, done: (err?: Error) => void) => void): any;
  /**
   * Retrieve a single target page of LocalInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param targetUrl - API-generated URL for the requested results page
   */
  getPage(targetUrl: string): Promise<LocalPage>;
  /**
   * Retrieve a single target page of LocalInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param targetUrl - API-generated URL for the requested results page
   * @param callback - Callback to handle processed record
   */
  getPage(targetUrl: string, callback: (error: Error | null, items: LocalPage) => any): void;
  /**
   * Lists LocalInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  list(opts?: LocalListOptions): Promise<LocalInstance[]>;
  /**
   * Lists LocalInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  list(opts: LocalListOptions, callback: (error: Error | null, items: LocalInstance[]) => any): void;
  /**
   * Lists LocalInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  list(callback: (error: Error | null, items: LocalInstance[]) => any): void;
  /**
   * Retrieve a single page of LocalInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   */
  page(opts?: LocalListPageOptions): Promise<LocalPage>;
  /**
   * Retrieve a single page of LocalInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  page(opts: LocalListPageOptions, callback: (error: Error | null, items: LocalPage) => any): void;
  /**
   * Retrieve a single page of LocalInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param callback - Callback to handle processed record
   */
  page(callback: (error: Error | null, items: LocalPage) => any): void;
}

declare class LocalPage extends Page<V2010, LocalPayload, LocalResource, LocalInstance> {
  constructor(version: V2010, response: Response<string>, solution: LocalSolution);

  /**
   * Build an instance of LocalInstance
   *
   * @param payload - Payload response from the API
   */
  getInstance(payload: LocalPayload): LocalInstance;
}

declare class LocalInstance {
  /**
   * @param version - Version of the resource
   * @param payload - The instance payload
   */
  constructor(version: V2010, payload: LocalPayload);

  private _proxy: LocalContext;
  /**
   * The account_sid
   */
  accountSid: string;
  /**
   * The address_requirements
   */
  addressRequirements: LocalAddressRequirement;
  /**
   * The address_sid
   */
  addressSid: string;
  /**
   * The api_version
   */
  apiVersion: string;
  /**
   * The beta
   */
  beta: boolean;
  /**
   * The capabilities
   */
  capabilities: string;
  /**
   * The date_created
   */
  dateCreated: Date;
  /**
   * The date_updated
   */
  dateUpdated: Date;
  /**
   * The friendly_name
   */
  friendlyName: string;
  /**
   * The identity_sid
   */
  identitySid: string;
  /**
   * The origin
   */
  origin: string;
  /**
   * The phone_number
   */
  phoneNumber: string;
  /**
   * The sid
   */
  sid: string;
  /**
   * The sms_application_sid
   */
  smsApplicationSid: string;
  /**
   * The sms_fallback_method
   */
  smsFallbackMethod: string;
  /**
   * The sms_fallback_url
   */
  smsFallbackUrl: string;
  /**
   * The sms_method
   */
  smsMethod: string;
  /**
   * The sms_url
   */
  smsUrl: string;
  /**
   * The status_callback
   */
  statusCallback: string;
  /**
   * The status_callback_method
   */
  statusCallbackMethod: string;
  /**
   * The trunk_sid
   */
  trunkSid: string;
  /**
   * The uri
   */
  uri: string;
  /**
   * The voice_application_sid
   */
  voiceApplicationSid: string;
  /**
   * The voice_caller_id_lookup
   */
  voiceCallerIdLookup: boolean;
  /**
   * The voice_fallback_method
   */
  voiceFallbackMethod: string;
  /**
   * The voice_fallback_url
   */
  voiceFallbackUrl: string;
  /**
   * The voice_method
   */
  voiceMethod: string;
  /**
   * The voice_url
   */
  voiceUrl: string;
}

export { LocalAddressRequirement, LocalInstance, LocalList, LocalListCreateOptions, LocalListEachOptions, LocalListInstance, LocalListOptions, LocalListPageOptions, LocalPage, LocalPayload, LocalResource, LocalSolution }
