/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import Version = require('../../base/Version');
import { CommandList } from './v1/command';
import { RatePlanList } from './v1/ratePlan';
import { SimList } from './v1/sim';


/**
 * Initialize the V1 version of Wireless
 */
declare class V1 extends Version {
  /**
   * Initialize the V1 version of Wireless
   *
   * @param domain - The twilio domain
   */
  constructor(domain: any);

  readonly commands: CommandList;
  readonly ratePlans: RatePlanList;
  readonly sims: SimList;
}

export = V1;
