/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */
/// <reference types="node" />

import Version = require('../../base/Version');
import { RecordingList } from './v1/recording';
import { RoomList } from './v1/room';


/**
 * Initialize the V1 version of Video
 */
declare class V1 extends Version {
  /**
   * Initialize the V1 version of Video
   *
   * @param domain - The twilio domain
   */
  constructor(domain: any);

  readonly recordings: RecordingList;
  readonly rooms: RoomList;
}

export = V1;
